### PR TITLE
Update Announcement.md

### PR DESCRIPTION
**Pull request by hughshanahan**
Fixed typo on email

### CODE REVIEW

**Comment by mkuzak** [comment]
good catch

**Comment by hughshanahan** [comment]
No worries! On the markdown the images look huge but we’ve constrained them to be about a cm wide. Will the HTML version do any better or should we make them smaller?

Hugh

**Comment by hughshanahan** [comment]
HI Mateusz
                     I think the minima theme will work better. There’s also a weird error message on the page where it shows a </table> </tbody> in the texst. Can you figure out what the problem might be there? Once we have that then we can announce it to the world.

Hugh

**Comment by mkuzak** [comment]
There was a mismatched tag. Now fixed, should be looking good. Fixed in commit 8dd3ede580ae08370bfab21c99a6d579fb411023

**Pull request merged**
